language: node_js
node_js:
- lts/boron
- node
sudo: false
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: IqPiKBV35U7oSqDrMs9aVSVjGPJ6M3S9c4nPTUBbDNSl4iUjyOsHm5hQoT4EGs66Qkaj2uRlDSdz44Majba/N2mPnYZTFBAvj+V3oCodmaF0PhMvFUVlKzA38ooDbZf6df9Hi1wxwb70QZbwxBw0vE4YmiumMiYWe1Eck3LZd2M=
  file:
    - "retext.js"
    - "retext.min.js"
  on:
    tags: true
